spring:
  application:
    name: oauth2-server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oauth2?useSSL=false&characterEncoding=utf8&useUnicode=true
    username: root
    password: syz951127
server:
  port: 8000

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml